service: s3EventDrivenIngestion
provider:
  name: aws
  runtime: python3.6
  region: ap-southeast-2
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:GetObject"
       Resource:
         Fn::Join:
           - ""
           - - "arn:aws:s3:::peterh-sydney-data-lake/*"

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    zip: true

functions:
  hello:
    handler: handler.hello
    events:
      - s3:
          bucket: peterh-sydney-data-lake
          event: s3:ObjectCreated:*
          rules:
            - suffix: .json